# 使用 CentOS 7.2 作为基础镜像
FROM centos:7

# 更新系统并安装 GCC 4.8.5
RUN yum -y update && \
    yum install gcc gcc-c++ glibc-static -y 

RUN yum -y install wget

RUN yum -y install git

# 安装 Python 3
RUN yum -y install python3

# 安装 Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# 安装 JDK 8
RUN yum -y install java-1.8.0-openjdk-devel

# # 安装 Maven
RUN wget https://repo.huaweicloud.com/apache/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz && \
    tar -xzf apache-maven-*.tar.gz && \
    mkdir -p /opt/maven && \
    mv apache-maven-* /opt/maven && \
    ln -s /opt/maven/apache-maven-3.9.6/bin/mvn /usr/bin/mvn